# Generated by Django 4.1.1 on 2022-09-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(max_length=2000, verbose_name='Текст')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField(default='0', verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('moderated', 'модерированная')], default='new', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'quotes',
            },
        ),
    ]
